package ark.coding.books.interview_kickstart.bit_manipulation;

import ark.coding.books.interview_kickstart.counting.CountWithArrayOrMap;

/**
 * XOR is a great operator for finding "Odd Man Out problems"
 */
public class XOR {

    /**
     * https://leetcode.com/problems/single-number/
     *
     * Given a non-empty array of integers, every element appears twice except for one. Find that single one.
     *
     * Note:
     * Your algorithm should have a linear runtime complexity. Could you implement it without using extra memory?
     *
     * Approach 4: Bit Manipulation
     * Concept
     *
     * If we take XOR of zero and some bit, it will return that bit
     * a ⊕ 0 = a ⊕ 0 = a
     * If we take XOR of two same bits, it will return 0
     * a ⊕ a = a ⊕ a = 0
     * a ⊕ b = b ⊕ a
     * a⊕b⊕a = (a⊕a)⊕b = 0⊕b = b
     *
     * An approach with Cyclic Sort was tried, but that clearly does not works
     *
     * @param nums
     * @return
     */
    public int singleNumber(int[] nums) {
        int singleNumber = nums[0];
        for (int index = 1; index < nums.length; index++) {
            singleNumber = singleNumber ^ nums[index];
        }
        return singleNumber;
    }

    /**
     * https://leetcode.com/problems/find-the-difference/
     *
     * Given two strings s and t which consist of only lowercase letters.
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     * Find the letter that was added in t.
     *
     * Approaches:
     * 1. Keep count of all lowercase alphabets - Time: O(n) Space: O(26) ~ O(1)
     *    {@link CountWithArrayOrMap#findTheDifference(String, String)}
     *
     * 2. XOR all characters in {@code s} and {@code t} Time:O(n) Space: O(1)
     *
     * @param s
     * @param t
     * @return
     */
    public char findTheDifference(String s, String t) {
        char extraLetter = 0;
        for (int idx = 0; idx < s.length(); idx++) {
            extraLetter ^= s.charAt(idx);
        }

        for (int idx = 0; idx < t.length(); idx++) {
            extraLetter ^= t.charAt(idx);
        }

        return extraLetter;
    }
}
