package ark.coding.books.interview_kickstart.counting;

public class CountWithArrayOrMap {

    /**
     * https://leetcode.com/problems/find-the-difference/
     *
     * Given two strings s and t which consist of only lowercase letters.
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     * Find the letter that was added in t.
     *
     * Approaches:
     * 1. Keep count of all lowercase alphabets - Time: O(n) Space: O(26) ~ O(1)
     *
     * 2. XOR all characters in {@code s} and {@code t} Time:O(n) Space: O(1)
     * {@link ark.coding.books.interview_kickstart.bit_manipulation.XOR#findTheDifference(String, String)}
     *
     * @param s
     * @param t
     * @return
     */
    public char findTheDifference(String s, String t) {
        int[] alphabetCount = new int[26]; // a-z are 26 characters

        for (int idx = 0; idx < s.length(); idx++) {
            int alphabetKey = s.charAt(idx) - 'a';
            alphabetCount[alphabetKey] = alphabetCount[alphabetKey] + 1;
        }

        char extraChar = t.charAt(0);
        spotExtraChar: for (int idx = 0; idx < t.length(); idx++) {
            int alphabetKey = t.charAt(idx) - 'a';
            if (alphabetCount[alphabetKey] == 0) {
                extraChar = t.charAt(idx);
                break spotExtraChar;
            }
            alphabetCount[alphabetKey] = alphabetCount[alphabetKey] - 1;
        }
        return extraChar;
    }
}
